### ISSUE TITLE
Create deployment and distribution checklist 

### ISSUE THREAD

**Issue by perionjames** [Periondao/perion-liquidity-mining#12]
- [ ] Run `full.ts` deploy script 
- [ ] Renounce role from deployer address 
- [ ] Approve token transfers from the gnosis safe 
- [ ] set `rewardPerSecond`
- [ ] Add distribute rewards transaction setup to gnosis safe
